export default {
  'header': {
    'summer sal-': 'Summer sale for all season plants and free express delivery - off 50%!',
    'home': 'home',
    'store': 'store',
    'blogs': 'blogs',
    'contact': 'contact us',
    'logging out': 'Logging out',
    'logged out': "You've logged out",
    'en': 'EN',
    'ge': 'GE',
    'profile': 'Profile',
    'orders': 'My orders',
    'logout': 'Log out',
    'sign in': 'Sign In',
    'welcome': 'welcome to the aurora plants',
    'intro text': "Let's Bring The Spring To Your Home",
    'shop now': 'shop now',
    'cart': 'Cart',
    'empty cart': 'Cart is empty',
    'subtotal': 'Subtotal',
    'start shopping': 'Start Shopping',
    'view cart': 'View Cart',
    'to proceed': 'To proceed you need to sign in',
    'go to login': 'Sign In'
  },
  'footer': {
    'support': 'get in touch',
    'address': 'city, example street',
    'links title': 'quick links',
    'store': 'store',
    'blogs': 'blogs',
    'contact': 'contact us',
    'info title': 'information',
    'terms & conditions': 'terms and conditions',
    'privacy policy': 'privacy policy',
    'sign in': 'sign in',
    'follow': 'follow us',
    'copy right text': 'Copyright Aurora Plants 2024. All right reserved'
  },
  '/': {
    'todays': "Today's",
    'flah sales': 'Flash Sales',
    'view all': 'view all products',
    'plants': 'Plants',
    'cactuses': 'Cactuses',
    'bonsais': 'Bonsais',
    'delivery service': ['free and fast delivery', 'Free delivery for all the orders over $140'],
    'support service': ['24/7 customer service', 'Friendly customer support 24/7'],
    'money back service': ['money back guarantee', 'we return money within 30 days']
  },
  '/sign-in': {
    'title': 'Sign in',
    'btn text': 'Log into account',
    'Login to yo-': 'Login to your account in a seconds',
    'remember': 'Keep me logged in',
    'forgot?': 'Forgot password?',
    'do not have and account?': "Don't have an account?",
    'sign up': 'Sign Up',
    'continue': 'or continue with',
    'email': 'Email',
    'password': 'Password',
    'incorrect credentials': 'Incorrect credentials! Please try again',
    'successfull login': "You've logged in successfully",
    'loading message': 'Logging in, it will take a few seconds',
    'failed login': 'Something went wrong, plase try again later'
  },
  '/sign-up': {
    'title': 'Sign Up',
    'btn text': 'Create and account',
    'create an acc-': 'create an account in just a seconds',
    'fill in a few-': 'fill in a few more fields',
    'credentials-': 'and credentials..',
    'agree to terms': 'I agree to ',
    'tac': 'Terms & Conditions',
    'already member?': 'Already a member?',
    'sign in': 'Sign In',
    'or continue': 'or continue with',
    'firstname': 'First Name',
    'lastname': 'Last Name',
    'gender': 'Gender',
    'male': 'male',
    'female': 'female',
    'dob': 'Date of Birth',
    'city': 'City',
    'address': 'Address',
    'mobile': 'Mobile Phone',
    'email': 'Email',
    'password': 'Password',
    'confirm': 'Confirm Paswword',
    'continue': 'continue',
    'go back': 'go back',
    'sign up': 'Sign Up',
    'email is used': 'Email is already used! Please enter different Email address',
    'successfull register': "You've registered successfully",
    'loading message': 'Please wait, it will take a few seconds',
    'failed registration': 'Something went wrong, plase try again later'
  },
  '/store': {
    'search': 'Search',
    'enter name': 'Enter product name',
    'filter': 'Filter',
    'select tags': 'Select tags',
    'tags': ['in sale', 'small', 'medium', 'large', 'slow-growing', 'fast-growing', 'flowering', 'non-flowering'],
    'price': 'Price',
    'categories': 'Categories',
    'plant': 'Plant',
    'cactus': 'Cactus',
    'bonsai': 'Bonsai',
    'reset': 'reset filter',
    'sort by': 'Sort by',
    'default': 'default',
    'sort-price': 'Price',
    'sort-price-desc': 'Price Desc',
    'no products': 'No Products Found'
  },
  '/product': {
    'add to cart': 'add to cart',
    'category': 'category',
    'plant': 'Plant',
    'cactus': 'Cactus',
    'bonsai': 'Bonsai',
    'growth': 'growth rate',
    'slow': 'slow',
    'fast': 'fast',
    'flowering': 'flowering',
    'seasonal flowering': 'seasonal flowering',
    'non-flowering': 'non-flowering',
    'pet frinedly': 'pet frinedly',
    'yes': 'yes',
    'no': 'no',
    'free shipping': 'Free shipping on orders over $140!',
    'money back': 'No-Risk Money Back Guarantee!',
    'refund': 'No hassle refunds',
    'payment': 'Secure payments',
    'description': 'Description',
    'reviews': 'Reviews',
  },
  '/cart': {
    'summary': 'Order Summary',
    'price': 'Price',
    'discount': 'discount',
    'shipping': 'shipping',
    'free': 'Free',
    'coupon applied': 'Coupon Applied',
    'total': 'Total',
    'proceed to checkout': 'Proceed to Checkout',
    'empty cart': 'Cart is empty',
    'remove': 'Remove'
  },
  '/checkout': {
    'contacts': 'Contact Details',
    'shipping': 'Shipping',
    'free': 'Free',
    'regular': 'Regular Shipping',
    'priority': 'Priority Shipping',
    'payment': 'Payment',
    'expires': ['Expires on', ''],
    'add payment': 'Add Payment Method',
    'continue': 'continue',
    'back': 'back',
    'submit': 'submit',
    'no payments': 'No active payment method found',
    'loading msg': 'Order is Proccessing',
    'success msg': 'Order successfully submitted',
    'error msg': 'Something went wring, try later'
  },
  '/contact': {
    'form': {
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone',
      'msg': 'Message',
      'send msg': 'Send Message'
    },
    'info': {
      'call to us': 'call us',
      'we are avail-': 'We are available 24/7, 7 days a week.',
      'phone': 'Phone',
      'write to us': 'write to us',
      'fill out our for-': 'Fill out our form and we will contact you within 24 hours.',
      'emails': 'Emails'
    }
  },
  '/profile': {
    'profile nav': {
      'manage my accaunt': 'manage my account',
      'my profile': 'my profile',
      'address book': 'address book',
      'my payment options': 'my payment options',
      'my orders': 'my orders',
      'my returns': 'my returns',
      'my cancelations': 'my cancelations'
    },
    'edit form': {
      'title': 'Edit Your Profile',
      'firstname': 'First Name',
      'lastname': 'Last Name',
      'gender': 'Gender',
      'male': 'male',
      'female': 'female',
      'mobile': 'Mobile',
      'dob': 'Date of Birth',
      'loading message': 'Processing',
      'success message': 'Changes Saved!',
      'failure message': 'Could not submit changes..',
      'password': ['Change Password', 'Current Password', 'New Password', 'Confirm New Password', 'change'],
      'cancel': 'Cancel',
      'save': 'Save Changes'
    },
    'addresses': {
      'edit': 'Edit',
      'remove': 'Remove',
      'contact': 'contact',
      'add address': 'Add New Address',
      'no addresses': 'No active address found',
      'city': ['City', 'Telavi'],
      'address': ['Address', 'D. Aghmashenebeli, 153'],
      'tag': ['Tag', 'Home, Office ...'],
      'add btn': 'save address',
      'loading msg': 'processing data',
      'success msg': 'address saved!',
      'failure msg': 'could not save address..'
    }
  }

} as const